package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/Holdrulff/autocomplete/internal/autocomplete"
)

// Autocomplete is the resolver for the autocomplete field.
func (r *queryResolver) Autocomplete(ctx context.Context, prefix string) ([]autocomplete.Suggestion, error) {
	return r.service.Search(prefix)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
